
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shive
 */
public class Adminuser2 extends javax.swing.JFrame {

    /**
     * Creates new form Adminuser2
     */
    public Adminuser2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1021, 648));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIQUID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 40, 310, 60);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 70, 22, 20);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GameName =");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 220, 170, 70);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Games in Store = ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 110, 170, 70);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "GNO", "GAME", "PRICE", "GENRE", "CREATOR"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 180, 550, 310);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(810, 190, 190, 26);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(810, 290, 190, 26);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(810, 340, 190, 26);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(810, 390, 190, 26);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 480, 160, 20);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 540, 160, 20);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(810, 240, 190, 26);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ENTER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(860, 120, 170, 70);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price =");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(700, 270, 170, 70);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Creator =");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(680, 370, 170, 70);

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Genre = ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(690, 320, 170, 70);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("GameNo =");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(670, 170, 170, 70);

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 530, 170, 30);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton4.setText("MODIFY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(840, 480, 160, 20);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 530, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (123)-1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1220, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            
        Connection conn=null;
        Statement stmt = null;
        String sql=null, game=null, genre=null, creator=null;
        int gno = 0, price = 0;
            conn = DriverManager.getConnection ("jdbc:mysql://localhost:3306/liquid", "root", "root");
            stmt = conn.createStatement();
           
 
            gno = Integer.parseInt(jTextField4.getText());
            game= jTextField8.getText();
            price= Integer.parseInt(jTextField5.getText());
            genre  = jTextField6.getText();
            creator = jTextField7.getText();
            

 sql = "insert into gamelist values (" + gno + ", '" + game + "' , " + price + " , '" + genre +  "', '" + creator + "');";

 
                
  if (gno>0 && price>0 && game.length()>0 && genre.length()>0 && creator.length()>0)
  
  {
        System.out.println(sql);
  stmt.executeUpdate(sql);
JOptionPane.showMessageDialog(null, "Addition Successful");

  }
  
     
    }                                        

                
        catch (Exception a)
                {System.out.println(a.getMessage());
                JOptionPane.showMessageDialog(this, "Invalid Details");
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
                try {
            
        Connection conn=null;
        Statement stmt = null;
        String sql=null, game=null, genre=null, creator=null, sql2=null;
        int gno = 0, price = 0;
            conn = DriverManager.getConnection ("jdbc:mysql://localhost:3306/liquid", "root", "root");
            
            stmt = conn.createStatement();
            
            gno = Integer.parseInt(jTextField4.getText());
           
            if (gno>0)
            {
            
 sql = "DELETE FROM gamelist where gno = " + gno + ";";

 
 
  System.out.println(sql);
            stmt.executeUpdate(sql);
             JOptionPane.showMessageDialog(null, "Delete Successful");
           
 
            }                    

            else JOptionPane.showMessageDialog(null, "please Enter Valid Gameno.");
                     
                }
            
        catch (Exception a)
                {System.out.println(a.getMessage());
                JOptionPane.showMessageDialog(null, "please Enter Valid Gameno.");
                }
        
                
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new Adminuser().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
        try { Connection conn= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/liquid", "root", "root");
        Statement stmt = (Statement) conn.createStatement();

        String sql = "Select gno, game, price, genre, creator from gamelist;";
        
        
        ResultSet rn = null;
        
       rn = stmt.executeQuery(sql);
        rn.first();
        
         for (int i = tm.getRowCount() - 1; i >= 0; i--)
        {
        tm.removeRow(i);
        }
        
        
        do
        {  tm.addRow(new Object[] {rn.getInt("gno"), rn.getString("game"), rn.getInt("price"), rn.getString("genre"), rn.getString("creator")});
        } 
        while (rn.next());
        
        
        
        }
        
        catch (Exception c)
        {System.out.println(c.getMessage());
        }     
                                      
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
     
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
              try {
            
        Connection conn=null;
        Statement stmt = null;
        String sql=null, game=null, genre=null, creator=null, sql2=null;
        int gno = 0, price = 0;
            conn = DriverManager.getConnection ("jdbc:mysql://localhost:3306/liquid", "root", "root");
            
            stmt = conn.createStatement();
            
            gno = Integer.parseInt(jTextField4.getText());
            game= jTextField8.getText();
            price= Integer.parseInt(jTextField5.getText());
            genre  = jTextField6.getText();
            creator = jTextField7.getText();
 
            if (gno>0 && price>0 && game.length()>0 && genre.length()>0 && creator.length()>0)
            {
            
 sql = "update gamelist set game = '" + game + "' , price = " + price + " , genre = '" + genre +  "', creator = '" + creator + "' where gno = " + gno + ";";

 
 
  System.out.println(sql);
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Update Successful");
 
            }                    

            else JOptionPane.showMessageDialog(null, "please Enter Valid Gameno and Details.");
                     
                }
            
        catch (Exception a)
                {System.out.println(a.getMessage());
                JOptionPane.showMessageDialog(null, "please Enter Valid Gameno and Details");
                }
        
                
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adminuser2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adminuser2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adminuser2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adminuser2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adminuser2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
