/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.*;
import javax.swing.JOptionPane;

/** 
 *
 * @author shive
 */
public class GAMES extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;

    /**
     * Creates new form GAMES
     */
    public GAMES() {
        initComponents(); }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1202, 688));
        getContentPane().setLayout(null);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Net Banking");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(840, 320, 130, 33);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 140, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Games");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 140, 140, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TM");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 80, 51, 20);

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LIQUID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 50, 390, 60);

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Need For Speed Payback");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 260, 370, 40);

        jLabel5.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PlayersUnknown Battlegrounds");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 390, 420, 50);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("COD");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(840, 380, 130, 33);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mode Of Payment");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(820, 140, 180, 30);

        jLabel6.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Counter Strike Global Offensive");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 470, 420, 37);

        jLabel2.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dark Souls Remastered");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 190, 360, 37);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Credit Card");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(840, 200, 130, 33);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Debit Card");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(840, 260, 130, 33);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Price");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(520, 140, 120, 30);

        jLabel4.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Call of Duty Black Ops III");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 330, 380, 40);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton1.setText("Details");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 230, 120, 20);

        jTextField5.setText("0");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(650, 470, 90, 26);

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(650, 190, 90, 26);

        jTextField4.setText("0");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(650, 400, 90, 26);

        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(650, 330, 90, 26);

        jTextField2.setText("0");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(650, 260, 90, 26);

        jLabel14.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("$50");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 190, 47, 37);

        jLabel13.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("$60");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(520, 260, 47, 37);

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$60");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(520, 330, 47, 37);

        jLabel16.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("$30");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(520, 400, 48, 37);

        jLabel17.setFont(new java.awt.Font("Jokerman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("$15");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(520, 460, 70, 50);

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton5.setText("Details");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(80, 370, 120, 20);

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton6.setText("Details");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(80, 440, 120, 20);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton4.setText("Details");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(80, 510, 120, 20);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jButton3.setText("Details");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(80, 300, 120, 20);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton2.setText("BUY");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(800, 550, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1 (123)-1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 664);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.setVisible(false);
        new DarkSoulsR().setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection conn=null;
        Statement stmt = null;
        String sql=null, query=null, mop = null, name=null, sql2 = null, game=null, ap=null, progress = null;
        int darksouls = 0, nfs = 0, cod = 0, pubg = 0, csgo = 0, total = 0;
        Random x = new Random();
        int n = x.nextInt(100000);
        String transid = "LI" + n; 
        progress = "ip";
        
        
        try {
            conn = DriverManager.getConnection ("jdbc:mysql://localhost:3306/liquid", "root", "root");
            stmt = conn.createStatement();
          sql2 = "select username from liquiduser where status = 'true';";
              ResultSet rs = stmt.executeQuery(sql2);
            rs.next();
            
           ap = rs.getString("username");
            
            darksouls = Integer.parseInt(jTextField1.getText());
            nfs = Integer.parseInt(jTextField2.getText());
            cod = Integer.parseInt(jTextField3.getText());
            pubg = Integer.parseInt(jTextField4.getText());
            csgo = Integer.parseInt(jTextField5.getText());
            
               
            
            if (jRadioButton1.isSelected())
            {
                mop = "credit card";
            if (darksouls > 0)
            {game = "DarkSoulsRemastered";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + darksouls +  ", " + darksouls*50 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}

            if (nfs>0)
            {sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + nfs +  ", " + nfs*60 + ", '" + mop + "' , '" + progress + "');";
            game = "NFS Payback";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
            if (cod > 0)
             {game = "CallofDuty Black Ops III";
             sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + cod +  ", " + cod*60 + ", '" + mop + "' , '" + progress + "');";
             System.out.println(sql);
             stmt.executeUpdate(sql);}
            
            
           if (pubg > 0)
            {game = "PlayerUnknown's Battlegrounds";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + pubg +  ", " + pubg*30 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
             if (csgo > 0)
            {game = "CounterStrike Go";           
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + csgo +  ", " + csgo*15 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
                                                                 
        this.setVisible(false);
        new Confirm().setVisible(true);
             
            }
            
            
            
             
 else if (jRadioButton2.isSelected())
     {mop = "debit card";
            
            if (darksouls > 0)
            {game = "DarkSoulsRemastered";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + darksouls +  ", " + darksouls*50 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}

            if (nfs>0)
            {sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + nfs +  ", " + nfs*60 + ", '" + mop + "' , '" + progress + "');";
            game = "NFS Payback";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
            if (cod > 0)
             {game = "CallofDuty Black Ops III";
             sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + cod +  ", " + cod*60 + ", '" + mop + "' , '" + progress + "');";
             System.out.println(sql);
             stmt.executeUpdate(sql);}
            
            
           if (pubg > 0)
            {game = "PlayerUnknown's Battlegrounds";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + pubg +  ", " + pubg*30 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
             if (csgo > 0)
            {game = "CounterStrike Go";           
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + csgo +  ", " + csgo*15 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);} 
                                       
        this.setVisible(false);
        new Confirm().setVisible(true);
             
             } 
             
            
            else  if (jRadioButton3.isSelected())
            {mop = "COD";
            
                        if (darksouls > 0)
            {game = "DarkSoulsRemastered";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + darksouls +  ", " + darksouls*50 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}

            if (nfs>0)
            {sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + nfs +  ", " + nfs*60 + ", '" + mop + "' , '" + progress + "');";
            game = "NFS Payback";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
            if (cod > 0)
             {game = "CallofDuty Black Ops III";
             sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + cod +  ", " + cod*60 + ", '" + mop + "' , '" + progress + "');";
             System.out.println(sql);
             stmt.executeUpdate(sql);}
            
            
           if (pubg > 0)
            {game = "PlayerUnknown's Battlegrounds";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + pubg +  ", " + pubg*30 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
             if (csgo > 0)
            {game = "CounterStrike Go";           
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + csgo +  ", " + csgo*15 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);} 
                                                                 
        this.setVisible(false);
        new Confirm().setVisible(true);
        
             }
            
            
            else  if (jRadioButton4.isSelected())
            {mop = "net banking";
            
                                    if (darksouls > 0)
            {game = "DarkSoulsRemastered";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + darksouls +  ", " + darksouls*50 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}

            if (nfs>0)
            {sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + nfs +  ", " + nfs*60 + ", '" + mop + "' , '" + progress + "');";
            game = "NFS Payback";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
            if (cod > 0)
             {game = "CallofDuty Black Ops III";
             sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + cod +  ", " + cod*60 + ", '" + mop + "' , '" + progress + "');";
             System.out.println(sql);
             stmt.executeUpdate(sql);}
            
            
           if (pubg > 0)
            {game = "PlayerUnknown's Battlegrounds";
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + pubg +  ", " + pubg*30 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);}
            
            
             if (csgo > 0)
            {game = "CounterStrike Go";           
            sql = "insert into liquidcart values ('" + transid + "', '" + ap + "' , '" + game + "' , " + csgo +  ", " + csgo*15 + ", '" + mop + "' , '" + progress + "');";
            System.out.println(sql);
            stmt.executeUpdate(sql);} 
                                                          
        this.setVisible(false);
        new Confirm().setVisible(true);
             
             }
            
            else JOptionPane.showMessageDialog(null, "Please select a Mode Of Payment");
   
            
        
            }
        

        catch (Exception a)
        {System.out.println(a.getMessage());
        JOptionPane.showMessageDialog(null, "Please select a Mode Of Payment");}
        

        
        
        
        
        
        
        
        
        
        
        
        

                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  this.setVisible(false);
        new NFS().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  this.setVisible(false);
        new CSGO().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  this.setVisible(false);
        new COD().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  this.setVisible(false);
        new PUBG().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GAMES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GAMES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GAMES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GAMES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GAMES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
